### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by ben21684** [iobroker-community-adapters/ioBroker.hid-community#49]
make: *** [HID.target.mk:120: Release/obj.target/HID/src/HID.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/node-hid/build“ wird verlassen
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.92-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/node-hid
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch"                                                                                                                          :"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2022-06-23T17_58_58_564Z-debug.log

**Comment by Apollon77** [comment]
Is this really all log? There should be more BEFORE your posted first line

**Comment by Apollon77** [comment]
Yes,m the used library is outdated for newer node.js versions and needs to be updated ... and some more stuff ...

**Comment by Apollon77** [comment]
@ben21684 Please try to istall GitHub version - https://github.com/iobroker-community-adapters/ioBroker.hid  Does it work now?

**Comment by Apollon77** [comment]
renamed to hid-community
