### ISSUE TITLE
Find Device funktioniert nicht, und VendorID/ProductID manuel eingeben geht auch nicht.

### ISSUE THREAD

**Issue by Coalado** [iobroker-community-adapters/ioBroker.hid-community#9]
Find Device: Dauert ewig - der Dialog bleibt einfach offen und es tut sich nichts.

Speichere ich die IDs manuel (als Decimalwert), erscheint in den Logs nur:

hid-community.0 | 2019-11-10 20:16:40.531 | error | If running on Windows, see requirements in readme.md. https://github.com/soef/iobroker.hid/blob/master/README.md
-- | -- | -- | --
hid-community.0 | 2019-11-10 20:16:40.530 | error | cannot open device with vendor id 0x46a and product id 0x180

Mein System ist ein RaspberryPI4 mit Rasbian.

Die IDs habe ich via terminal ausgelesen:
pi@raspberrypi:~ $ sudo lsusb
....
....
Bus 001 Device 004: ID 046a:0180 Cherry GmbH 

Irgendwelche Ideen?

**Comment by Coalado** [comment]
Halb gelöst: Unter Linux muss man eine udev device permission setzen. Ohne diese hat ioBroker keinen Zugriff auf das Gerät. 
https://github.com/node-hid/node-hid#udev-device-permissions

Das sollte mit in die Readme aufgenommen werden.

Find Device geht aber leider trotzdem nicht. Dafür habe ich bisher noch keine Lösung.

**Comment by Apollon77** [comment]
aufgenommen. Bitte nochmal mit allen Details aus der (neuen) Readme die GitHub version (achtung: Adaptername changes zu https://github.com/iobroker-community-adapters/ioBroker.hid !) versuchen

**Comment by Apollon77** [comment]
Please also run with debug logging and post log from a discovery try
